  server:
  host: "0.0.0.0"  # Use 0.0.0.0 for external access
  port: 7860
  external_access: false  # Set to true to enable external access
  auth_enabled: true     # Set to false to disable authentication
  username: "admin"      # Change this in production
  password: "admin123"   # Change this in production
  ssl_enabled: false     # Set to true to enable HTTPS
  ssl_cert: ""          # Path to SSL certificate
  ssl_key: ""           # Path to SSL private key

storage:
  upload_dir: "uploaded_files"
  scan_dir: "scanned_files"

printing:
  default_printer: ""  # Leave empty to use system default
  allowed_extensions:
    - .pdf
    - .doc
    - .docx
    - .txt

scanning:
  default_format: "pdf"
  resolution: 300
  color_mode: "color"  # color or grayscale